# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: RSS3 Node Dev
spec:
    description: Deploy a RSS3 Node Dev easily!
    coverImage: https://a-us.storyblok.com/f/1018186/2600x1420/59d1051f18/chips.png
    icon: https://avatars.githubusercontent.com/u/152575164?s=48&v=4
    variables:
        - key: EVM_ADDRESS
          type: STRING
          name: What is your operator evm address?
          description: Used for the operator evm address for your node.
        - key: SIGNATURE
          type: STRING
          name: What is your operator signature?
          description: Used for the operator signature for your node.
        - key: ACCESS_TOKEN
          type: STRING
          name: What is your access token?
          description: Used for the access token for your node api.
        - key: WEB_URL
          type: DOMAIN
          name: What is your domain for the node?
          description: Used for expose the node to the public web.
    tags:
        - web3
    readme: |
        ## Description
        The RSS3 Node, an RSS3 Data Sublayer (DSL) component, is responsible for indexing, transforming, storing, and ultimately serving the Open Information to the end users.

        ## Register Your Node

        ![register](https://a-us.storyblok.com/f/1018186/2001x1437/25f760d323/alphanodes.png)

        You can check [this doc](https://docs.rss3.io/guide/for-node-operators/node-deployment-guide) from RSS3 team for a more detailed guide for registering a node.

        ## The Mainnet Explorer

        One of the best ways to interact with the Mainnet is through the RSS3 Explorer.

        ![Explorer](https://a-us.storyblok.com/f/1018186/2100x1864/8ef489d9c0/explorer.png)
    services:
        - name: cockroachdb
          icon: https://coralogix.com/wp-content/uploads/2024/02/CockroachDB-1000X1000.png
          template: PREBUILT
          spec:
            source:
                image: cockroachdb/cockroach:v23.1.8
                command:
                    - ./cockroach
                    - start-single-node
                    - --insecure
            ports:
                - id: native
                  port: 26257
                  type: TCP
                - id: http
                  port: 8080
                  type: HTTP
            volumes:
                - id: data
                  dir: /cockroach/cockroach-data
            env:
                COCKROACHDB_CONNECTION_STRING:
                    default: postgres://${COCKROACHDB_USER}@${COCKROACHDB_HOST}:${COCKROACHDB_PORT}/${COCKROACHDB_DB}
                    expose: true
                    readonly: true
                COCKROACHDB_DB:
                    default: defaultdb
                    expose: true
                    readonly: true
                COCKROACHDB_HOST:
                    default: ${CONTAINER_HOSTNAME}
                    expose: true
                    readonly: true
                COCKROACHDB_PORT:
                    default: "26257"
                    expose: true
                    readonly: true
                COCKROACHDB_USER:
                    default: root
                    expose: true
                    readonly: true
        - name: Redis
          icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/redis.svg
          template: PREBUILT
          spec:
            source:
                image: redis/redis-stack-server:latest
            ports:
                - id: database
                  port: 6379
                  type: TCP
            volumes:
                - id: data
                  dir: /data
            instructions:
                - type: TEXT
                  title: Command to connect to your Redis
                  content: redis-cli -h ${PORT_FORWARDED_HOSTNAME} -p ${DATABASE_PORT_FORWARDED_PORT} -a ${REDIS_PASSWORD}
                - type: TEXT
                  title: Redis Connection String
                  content: redis://:${REDIS_PASSWORD}@${PORT_FORWARDED_HOSTNAME}:${DATABASE_PORT_FORWARDED_PORT}
                - type: PASSWORD
                  title: Redis password
                  content: ${REDIS_PASSWORD}
                  category: Credentials
                - type: TEXT
                  title: Redis host
                  content: ${PORT_FORWARDED_HOSTNAME}
                  category: Hostname & Port
                - type: TEXT
                  title: Redis port
                  content: ${DATABASE_PORT_FORWARDED_PORT}
                  category: Hostname & Port
            env:
                REDIS_ARGS:
                    default: --requirepass ${REDIS_PASSWORD}
                REDIS_CONNECTION_STRING:
                    default: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
                    expose: true
                    readonly: true
                REDIS_HOST:
                    default: ${CONTAINER_HOSTNAME}
                    expose: true
                    readonly: true
                REDIS_PASSWORD:
                    default: ${PASSWORD}
                    expose: true
                REDIS_PORT:
                    default: ${DATABASE_PORT}
                    expose: true
                    readonly: true
                REDIS_URI:
                    default: ${REDIS_CONNECTION_STRING}
                    expose: true
                    readonly: true
        # - name: RSSHub
        #   icon: https://docs.rsshub.app/logo.png
        #   template: PREBUILT
        #   spec:
        #     source:
        #         image: diygod/rsshub
        #     ports:
        #         - id: web
        #           port: 1200
        #           type: HTTP
        #     env:
        #         CACHE_TYPE:
        #             default: redis
        #         REDIS_URL:
        #             default: ${REDIS_URI}
        - name: RSS3-Node-Broadcaster
          icon: https://explorer.rss3.io/rss3.svg
          template: PREBUILT
          spec:
            source:
                image: ghcr.io/rss3-network/node:v0.5.32
                command:
                    - ./node
                    - --module=broadcaster
            env:
                NODE_DISCOVERY_OPERATOR_EVM_ADDRESS:
                    default: ${EVM_ADDRESS}
                NODE_DISCOVERY_OPERATOR_SIGNATURE:
                    default: ${SIGNATURE}
                NODE_DISCOVERY_SERVER_ACCESS_TOKEN:
                    default: ${ACCESS_TOKEN}
                NODE_DISCOVERY_SERVER_ENDPOINT:
                    default: ${ZEABUR_WEB_URL}
                NODE_DISCOVERY_SERVER_GLOBAL_INDEXER_ENDPOINT:
                    default: https://gi.rss3.dev
                NODE_OBSERVABILITY_OPENTELEMETRY_METRICS_ENABLE:
                    default: "false"
                NODE_OBSERVABILITY_OPENTELEMETRY_TRACES_ENABLE:
                    default: "false"
        - name: RSS3-Node-Core
          icon: https://explorer.rss3.io/rss3.svg
          template: PREBUILT
          spec:
            source:
                image: ghcr.io/rss3-network/node:v0.5.32
                command:
                    - ./node
                    - --module=core
            ports:
                - id: web
                  port: 80
                  type: HTTP
            env:
                NODE_DATABASE_URI:
                    default: ${COCKROACHDB_CONNECTION_STRING}
                NODE_DISCOVERY_OPERATOR_EVM_ADDRESS:
                    default: ${EVM_ADDRESS}
                NODE_DISCOVERY_OPERATOR_SIGNATURE:
                    default: ${SIGNATURE}
                NODE_DISCOVERY_SERVER_ACCESS_TOKEN:
                    default: ${ACCESS_TOKEN}
                NODE_DISCOVERY_SERVER_ENDPOINT:
                    default: ${ZEABUR_WEB_URL}
                NODE_DISCOVERY_SERVER_GLOBAL_INDEXER_ENDPOINT:
                    default: https://gi.rss3.dev
                NODE_OBSERVABILITY_OPENTELEMETRY_METRICS_ENABLE:
                    default: "false"
                NODE_OBSERVABILITY_OPENTELEMETRY_TRACES_ENABLE:
                    default: "false"
                NODE_REDIS_ENDPOINT:
                    default: ${REDIS_HOST}:${REDIS_PORT}
                NODE_REDIS_PASSWORD:
                    default: ${REDIS_PASSWORD}
          domainKey: WEB_URL
        - name: RSS3-Node-Monitor
          icon: https://explorer.rss3.io/rss3.svg
          template: PREBUILT
          spec:
            source:
                image: ghcr.io/rss3-network/node:v0.5.32
                command:
                    - ./node
                    - --module=monitor
            env:
                NODE_DATABASE_URI:
                    default: ${COCKROACHDB_CONNECTION_STRING}
                NODE_REDIS_ENDPOINT:
                    default: ${REDIS_HOST}:${REDIS_PORT}
                NODE_REDIS_PASSWORD:
                    default: ${REDIS_PASSWORD}
        - name: RSS3-Node-VSL-Core
          icon: https://explorer.rss3.io/rss3.svg
          template: PREBUILT
          spec:
            source:
                image: ghcr.io/rss3-network/node:v0.5.32
                command:
                    - ./node
                    - --worker.id=vsl-core
            env:
                NODE_DATABASE_URI:
                    default: ${COCKROACHDB_CONNECTION_STRING}
                NODE_OBSERVABILITY_OPENTELEMETRY_METRICS_ENABLE:
                    default: "false"
                NODE_OBSERVABILITY_OPENTELEMETRY_TRACES_ENABLE:
                    default: "false"
                NODE_REDIS_ENDPOINT:
                    default: ${REDIS_HOST}:${REDIS_PORT}
                NODE_REDIS_PASSWORD:
                    default: ${REDIS_PASSWORD}